### ISSUE TITLE
Error: Cannot find module 'Youch'

### ISSUE THREAD

**Issue by gideaoms** [adonisjs/adonis-ignitor#10]
Hello,

I'm trying to format the errors with Youch, but I'm getting a mistake.

I'm importing Youch as follows: 

const Youch = use('Youch')

Error: Cannot find module 'Youch'
Error: Cannot find module 'Youch'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireStack (/usr/app/node_modules/require-stack/src/index.js:44:12)
    at Ioc._require (/usr/app/node_modules/@adonisjs/fold/src/Ioc/index.js:345:12)
    at Ioc.use (/usr/app/node_modules/@adonisjs/fold/src/Ioc/index.js:742:17)
    at Object.<anonymous> (/usr/app/app/Exceptions/Handler.js:5:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireStack (/usr/app/node_modules/require-stack/src/index.js:44:12)

**Comment by thetutlage** [comment]
You don't have to manually import youch and use it. Simply make use of global exception handler https://adonisjs.com/docs/4.1/exceptions#_wildcard_handler.

**Comment by gideaoms** [comment]
I want to return the error in JSON format for api:
`
if (Env.get('NODE_ENV') === 'development') {
      const youch = new Youch(error, request.request)
      const errorJSON = await youch.toJSON()
      return response.status(error.status).send(errorJSON)
}
`
What is the correct way to do this?

**Comment by thetutlage** [comment]
Youch will return error in JSON, if your request has `Accept: application/json` header. You won't have to do anything extra for that

**Comment by lucassp12** [comment]
Good Night!

Brother, The error is in the import the correct is youch in the place of Youch.
const Youch = use(‘Youch’) = error
const Youch = use(‘youch’) = Correct

Hope this helps!

**Comment by lcnogueira** [comment]
Thanks a lot, @lucassp12 :+1:

**Comment by higoncesar** [comment]
Thanks, @lucassp12

**Comment by mateus4k** [comment]
Thanks, @lucassp12! :1st_place_medal:

**Comment by douglasmartins7** [comment]
Thanks a lot @lucassp12

**Comment by douglasbrandao** [comment]
> Good Night!
> 
> Brother, The error is in the import the correct is youch in the place of Youch.
> const Youch = use(‘Youch’) = error
> const Youch = use(‘youch’) = Correct
> 
> Hope this helps!

Thank you, @lucassp12

**Comment by xKmz** [comment]
> Good Night!
> 
> Brother, The error is in the import the correct is youch in the place of Youch.
> const Youch = use(‘Youch’) = error
> const Youch = use(‘youch’) = Correct
> 
> Hope this helps!

Thank you! <3

**Comment by diegolsr** [comment]
Thanks a lot, @lucassp12 🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by Losangelo** [comment]
I was making the same mistake, thanks!

**Comment by eloysge** [comment]
> Good Night!
> 
> Brother, The error is in the import the correct is youch in the place of Youch.
> const Youch = use(‘Youch’) = error
> const Youch = use(‘youch’) = Correct
> 
> Hope this helps!

agora sim! uma resposta correta
